---
- name: remote setting
  hosts: zabbix-agent
  remote_user: root
  become: yes
  become_method: sudo
  vars: 
    remote_host: 192.168.5.41

  tasks:
   - name: install zabbix rpm from remote repo
     yum: 
       name: "http://repo.zabbix.com/zabbix/2.4/rhel/6/x86_64/zabbix-release-2.4-1.el6.noarch.rpm" 
       state: present
       
   - name: install zabbix-agent
     yum: name=zabbix-agent state=present

   - name: config zabbix setting
     lineinfile: dest=/etc/zabbix/zabbix_agentd.conf regexp="^Server=" line="Server=127.0.0.1,{{ remote_host }}" 

   - name: add rule to  iptables
     lineinfile: dest=/etc/sysconfig/iptables regexp="^-A" insertafter="^:OUTPUT " line="-A INPUT -p tcp  --dport 10050  -j  ACCEPT"   
   
   - name: restart iptables
     service: name=iptables state=restarted
   
   - name: start zabbix-agent
     service: name=zabbix-agent state=started enabled=yes

